apiVersion: v1
kind: Secret
metadata:
  name: my-npmrc
type: Opaque
stringData:
  # Example .npmrc file content, fill it with your actual configuration
  .npmrc: |
    @redhat:registry=https://npm.registry.my-npmrc.com
---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: my-rhdh
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            initContainers:
              - name: install-dynamic-plugins
                volumeMounts:
                  - mountPath: /opt/app-root/src/.my-npmrc.dynamic-plugins
                    name: my-npmrc
                env:
                  - name: NPM_CONFIG_USERCONFIG
                    # path before .npmrc should be the same as in the mountPath above
                    # file name .npmrc should be the same as key in the secret above
                    value: /opt/app-root/src/.my-npmrc.dynamic-plugins/.npmrc
            volumes:
              - name: my-npmrc
                secret:
                  name: my-npmrc
                  secretName: my-npmrc
