apiVersion: v1
kind: Secret
metadata:
  name: dynamic-plugins-npmrc
  annotations:
    rhdh.redhat.com/mount-path: /opt/app-root/src/.npmrc.dynamic-plugins
    rhdh.redhat.com/containers: install-dynamic-plugins
type: Opaque
stringData:
  val: |
    {{$value-of: {kind:secrets,name:my-secret,jsonpath:$.data.val}}}



